@startuml

object "<u>course:Course</u>" as c {
    courseName = "CS 3560"
}

object "<u>instructor1:Instructor</u>" as i1 {
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
}

object "<u>textbook1:Textbook</u>" as t1 {
    title = "Clean Code"
    author = "Robert C. Martin"
    publisher = "Prentice Hall"
}

c o-- i1 : instructor
c o-- t1 : textbook

@enduml
