@startuml

object "course : Course" as course {
    courseName = "CS 3560"
}

object "instructor1 : Instructor" as instructor1 {
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
}

object "textbook1 : Textbook" as textbook1 {
    title = "Clean Code"
    author = "Robert C. Martin"
    publisher = "Prentice Hall"
}

course o-- instructor1 : instructor
course o-- textbook1 : textbook

@enduml
