@startuml

object "<u>ships:Ship[]</u>" as sa {
    length = 3
}

object "<u>titanic:Ship</u>" as ts {
    name = "Titanic"
    yearBuilt = "1912"
}

object "<u>royalPrincess:CruiseShip</u>" as rp {
    name = "Royal Princess"
    yearBuilt = "2013"
    maxPassengers = 3600
}

object "<u>everGiven:CargoShip</u>" as eg {
    name = "Ever Given"
    yearBuilt = "2018"
    cargoCapacity = 200000
}

sa --> ts : [0]
sa --> rp : [1]
sa --> eg : [2]

@enduml
